### ISSUE TITLE
The corresponding Python version

### ISSUE THREAD

**Issue by licj1** [saarmichael/Flight-Anomaly-Detection#1]
Hello,
Thanks for your excellent work, I would like to know if there is a corresponding python version of the program? I Look forward to your reply. Thanks!

**Comment by saarmichael** [comment]
Hi there, 
unfortunatly I don't have a corresponding python version.
Let me ask you though- what's intersting to you in this project? This is a homework rolling project for second year CS students, and we never thought anyone would find it interesting at all.
